# Node 10.x
FROM node:10-alpine

# Add bin deps to image.
RUN apk update && apk add bash

# Create app directory.
WORKDIR /var/www/ec-api

# Install NPM production deps and cleanup.

RUN npm install -g cnpm --registry=https://registry.npm.taobao.org

COPY package*.json ./

RUN cnpm i

COPY . .

RUN npx rimraf ./dist
RUN npx babel ./src --out-dir ./dist

# Run and restart on changes.
CMD node ./dist/index.js
